
# artist1 = Artist.create!(profilePic: "https://s.abcnews.com/images/Lifestyle/puppy-ht-3-er-170907_4x3_992.jpg", username: "PuppyDog", location: "New York, NY", category: "Graffiti", bio: "Cool dawg", feature: "https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/cute-graffiti-dog-yurix-sardinelly.jpg", rate: 299, phone: 555-555-5555, email: "cooldawg@gmail.com", website: "www.dogart.com", password_digest: "password" ) 

artist1 = Artist.create!(profilePic: "http://convicts.nyc/app/uploads/2018/01/Zephyr-Tag-from-the-mid-1980s.jpg", username: "Zephyr (Andrew Witten)", location: "New York, NY", category: "Graffiti", bio: "A legendary New York City graffiti artist who emerged from the Bandshell scene of the 1970s. He is one of the graffiti writers who helped jumpstart the freight train graffiti movement, and is often credited as the inventor of numerous graffiti styles still widely used today. Zephyr began his street art career in 1977 by writing his tag on freight trains and subway cars, which is the main reason why much of his earliest work is now forever lost. He quickly rose to prominence and was part of the first wave of graffiti artists to make commercial success and transition to galleries. Today, 54-year-old Zephyr is considered a graffiti elder, but cannot resist the urge and often tags his name on walls around the city.", feature: "http://zephyrgraffiti.com/wp-content/uploads/2019/05/Screen-Shot-2019-02-25-at-9.56.03-AM.png", rate: 599, phone: "516-948-3849", email: "info@zephyrgraffiti.com", website: "http://zephyrgraffiti.com/", password_digest: "password")

artist2 = Artist.create!(profilePic: "https://www.themodern.org/sites/default/files/10-26a.png", username: "Kenny Scharf", location: "Brooklyn, NY", category: "Graffiti", bio: "My ambition as a professional artist is to maintain the course that I set 30 years ago by establishing my work in the fields of painting, sculpture, and performance. Every project I undertake is building on my past experiences. My original approach is unchanged; it is a personal challenge to produce the best work possible every time. One very important and guiding principle to my work is to reach out beyond the elitist boundaries of fine art and connect to popular culture through my art. My personal ambition has always been to live the example.", feature: "https://i1.wp.com/www.lataco.com/wp-content/uploads/2_HOMPAGE.jpg?resize=1400%2C600&", rate: 799, phone: "516-378-2299", email: "info@kennyscharf.com", website: "https://kennyscharf.com/", password_digest: "password")

artist3 = Artist.create!(profilePic: "http://voyagela.com/wp-content/uploads/2019/03/personal_photo.jpeg-60-782x600.jpg", username: "Cernesto", location: "New York, NY", category: "Street Art", bio: "Cern, a native of New York City currently based in Brooklyn, got his start writing graffiti in the early nineties.  Continued development as a visual artist and musician finds Cern painting murals and exhibiting works throughout South America, Europe and South Africa. Cern’s work has also been featured at the San Diego Museum of Art, Museu Brasileiro De Escultura in Sao Paulo, and Los Angeles MOCA.", feature: "https://cernesto.files.wordpress.com/2013/10/img_9545.jpg?w=2045&h=1534", rate: 299, phone: "718-538-4929", email: "Cernone@gmail.com", website: "https://cernesto.com/", password_digest: "password")

artist4 = Artist.create!(profilePic: "https://d2jv9003bew7ag.cloudfront.net/uploads/briansines.jpg", username: "Brandon Sines", location: "Brooklyn, NY", category: "Street Art", bio: "Brandon Sines has a poetic ability to share intimate moments laced with popular imagery. He creates paintings dripping in personal narrative and puddled with external references. They are immediate both in subject and use of material, yet there is an intangible aspect that beckons the active imagination. He mixes Pop Art’s mass culture, Surrealism’s private associations, and the intuitive paint handling of Expressionism to create dreamlike environments.", feature: "https://images.squarespace-cdn.com/content/v1/58d16f4d29687f28d960c7d6/1548166620769-1P2XQP3MNCTKKMSAT2GK/ke17ZwdGBToddI8pDm48kKCOq53QVhH2MQLroQIMOK0UqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcnXlzez4jfKQH5DkzeZj1y-1MzKtB17BHdMx3ZGfR6vNi_ABftlPqvmdtbR-KaFai/Frank+Happy+TIme+NYC+2019.jpg?format=1500w", rate: 399, phone: "495-993-0293", email: "info@sinesart.com", website: "http://www.sinesart.com/", password_digest: "password")

artist5 = Artist.create!(profilePic: "https://images.squarespace-cdn.com/content/v1/575599d11bbee0f4903a3b84/1498773579927-TLE3ATHWD6F1IZDOHXZD/ke17ZwdGBToddI8pDm48kLjLkCOJsB_8buHtnU2wxFx7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1USSmc9zb8yYpgCH3XU1dP-v59c7iGwicwArSLjXM1TZwtrU8UFk4BXyUXL-Dw_TrVg/Hektad+.JPG?format=2500w", username: "Hektad", location: "New York, NY", category: "Graffiti/Street Art", bio: "Hektad is a New York City graffiti pioneer. In 1982, at the age of 12, the Bronx native set out to compete with veteran bombers such as Mitch 77 and Chris 217. After an intense 12 year campaign on New York’s streets and transit system, Hektad took a well deserved break to focus on his family. In 2013, he returned with a vengeance. After jumping into what many consider a cluttered and undefined street art scene, Hektad clearly took the lead with his whimsical “Love Drunk” hearts and humorous anecdotes. Currently, Hek is experimenting with many new mediums tinged with traditional graffiti. With this current collection of pieces, it is evident that Hektad is well on his way to securing a permanent spot in the annals of New York street art history.", feature: "http://www.about-street-art.com/wp-content/uploads/2016/10/HEDTAK_Manhattan01.jpg", rate: 499, phone: "229-049-5583", email: "HektadArt@gmail.com", website: "https://hektad.com/", password_digest: "password")

artist6 = Artist.create!(profilePic: "http://www.coneyartwalls.com/content/1-current-murals/7-d-f/3_acooperdface0301.jpg", username: "D*Face (Dean Stockton)", location: "London, UK", category: "Urban Contemporary", bio: "D*Face a.k.a Dean Stockton has been a leading figure in Urban Contemporary Art, inaugurating his career on the streets over 15 years ago by hand-drawing stickers and posters and adhering them for the unsuspecting public to discover in the streets of London and beyond. He is one of the best-known figures to rise from the British scene having had a constant leading presence throughout its meteoric rise into popular culture.", feature: "https://images.squarespace-cdn.com/content/v1/5a1acb6ff9a61edc99dc6a37/1511899799622-KUQUGOH2S7K1V3496HGM/ke17ZwdGBToddI8pDm48kDHPSfPanjkWqhH6pl6g5ph7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0mwONMR1ELp49Lyc52iWr5dNb1QJw9casjKdtTg1_-y4jz4ptJBmI9gQmbjSQnNGng/Date+With+Death+NYC+Coney+Island+June+2016.JPG?format=2500w", rate: 599, phone: "698-110-8884", email: "CONTACT@DFACE.CO.UK", website: "http://www.dface.co.uk/", password_digest: "password")

artist7 = Artist.create!(profilePic: "https://media.wmagazine.com/photos/5810efa08207661517c63252/2:3/w_640/arar_ya_abney_v.jpg", username: "Nina Chanel Abney", location: "Chicago, IL", category: "Cultural Collage/Mural", bio: "My work uses bold, bright color and collage-style imagery to examine and loosen the dialogue about race, culture and gender. My paintings are typically large, almost mural-like and are largely influenced by the merging of celebrity news reports, politicians, American culture and the drama of everyday life.", feature: "http://www.coneyartwalls.com/thumbs/5_acooperninachanelabney8335-17ae4f05ce199501b6d61f5109eaced1.jpg", rate: 299, phone: "883-384-7736", email: "NinaChanelAbney@gmail.com", website: "https://ninachanel.com/", password_digest: "password")

artist8 = Artist.create!(profilePic: "https://hips.hearstapps.com/ell.h-cdn.co/assets/15/24/2560x3602/gallery-1433980958-kashink-portrait.jpg?resize=480:*", username: "Kashink", location: "Paris, France", category: "Graffiti/Street Art", bio: "KASHINK is one of the few very active female artists in the French graffiti/street art scene. She lives in Paris, France, and has travelled a lot throughout the world, getting inspiration from many different cultures. She paints huge four eyed characters, with thick lines, vivid colors, in a very distinctive style. KASHINK is a surprising person: as most female painters represent female figures, she only paints men, preferably fat and hairy, looking like badass yet sensitive gangsters, alien-looking ogers, or shamans from ancient tribes. Some of them are gay, some of them are killers, some others are both. She's provocative, creative, constantly challenging.", feature: "http://www.coneyartwalls.com/thumbs/ecooperkashink7124-b52b394353d459c21ccf95d743482e24.jpg", rate: 699, phone: "019-493-7771", email: "Kashink@gmail.com", website: "https://kashink.com/", password_digest: "password")

artist9 = Artist.create!(profilePic: "https://d2zyqkholbutip.cloudfront.net/tristen_large_1.jpg", username: "Tristan Eaton", location: "Los Angeles, CA", category: "Street Art", bio: "Born in LA in 1978, Tristan Eaton started pursuing street art as a teenager, painting everything from billboards to dumpsters in the urban landscapes of the cities where he lived, be it London, Detroit, or New York. He designed his first toy for Fisher-Price at 18 years old and soon became a driving force in the world of designer toys. Eaton's work for Kidrobot, including the famous Dunny and Munny art toys, helped him achieve international renown and an ever-growing fan base. After forming his Creative Agency Thunderdog Studios in New York City in 2004, Eaton became a leader in the advertising and commercial-art spheres, and is regularly commissioned by a roster of clients that includes Nike, Versace, and even Barack Obama.", feature: "http://www.coneyartwalls.com/content/1-current-murals/35-tristan-eato/6_acoopertristaneaton8711-recovered.jpg", rate: 499, phone: "772-550-4205", email: "TristanEaton@gmail.com", website: "https://tristaneaton.com/", password_digest: "password")

artist10 = Artist.create!(profilePic: "https://cdn.shopify.com/s/files/1/0541/2661/files/Photo_5-16-19_6_59_49_PM_1024x1024.jpg?v=1559144657", username: "Sticky Monger", location: "New York, NY", category: "Street Art/Murals", bio: "Stickymonger is a New York-based artist whose giant murals transform ordinary spaces into eerie, dreamlike, parallel universes. Looking into the the large eyes of her animation-inspired subjects, the viewer is invited to explore the interplay of darkness and light, as well as the tension between innocence and fear, femininity and anxiety. ", feature: "https://images.squarespace-cdn.com/content/v1/5304fae7e4b0658094be30e6/1538379456135-Q1Z0DJ7JV91DAKZCZ2IB/ke17ZwdGBToddI8pDm48kLkXF2pIyv_F2eUT9F60jBl7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0iyqMbMesKd95J-X4EagrgU9L3Sa3U8cogeb0tjXbfawd0urKshkc5MgdBeJmALQKw/STICKYMONGER_2WTC-12_s.jpg?format=2500w", rate: 599, phone: "105-298-4355", email: "StickyMonger@gmail.com", website: "http://www.stickymonger.com/", password_digest: "password")

